// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface IconMetadata {
  host: string;
  asset_url_pattern: string;
  families: string[];
  icons: IconElement[];
}

export interface IconElement {
  name: string;
  version: number;
  popularity: number;
  unsupported_families: never[];
  categories: string[];
  tags: string[];
  sizes_px: number[];
}
